version: "3.7"

networks:
    app-network:
        driver: bridge

services:
    app:
        container_name: app
        build:
            context: ./docker/app
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-network
        depends_on:
            - db

    db:
        container_name: pgsql
        build:
            context: ./docker/pgsql
            dockerfile: Dockerfile
        image: pgsql-docker
        restart: unless-stopped
        expose:
            - "5432"
        ports:
            - "5433:5432"
        volumes:
            - ./docker/pgsql/script:/docker-entrypoint-initdb.d
            - ./docker/pgsql/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        networks:
            - app-network

    nginx:
        image: nginx:1.19.8-alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        ports:
            - "8100:80"
        depends_on:
            - app
        links:
            - app
        volumes:
            - ./docker/nginx/conf:/etc/nginx/conf.d
            - ./:/var/www
        networks:
            - app-network